### ISSUE TITLE
Edit HTML-option

### ISSUE THREAD

**Issue by websupporter** [youknowriad/gcf#18]
Sorry for my ignorance, I do not know your project quite well (yet), I was just playing a bit with it here https://frontenberg.tomjn.com/frontenberg_demo_pro/parachute/

I noticed, the option "Edit as HTML" is still present:
![screenshot-2018-1-31 the scream - frontenberg](https://user-images.githubusercontent.com/6458412/35624252-24c9c790-0697-11e8-865e-b0ff3016bbf7.png)

For these blocks, they should be removed.

Reference:
https://twitter.com/riadbenguella/status/958682122713051136

**Comment by youknowriad** [comment]
Thanks for opening the issue, I'll try to address this as soon as I can.
