### ISSUE TITLE
GCF template do not appear in existing posts

### ISSUE THREAD

**Issue by MarieComet** [youknowriad/gcf#26]
Hi Riad,
It seem custom fields templates does not appear in posts published **before** custom fields templates creation.
I'm using WP 4.9.4 with Gutenberg from the Github repo (master branch).

**Comment by youknowriad** [comment]
Yes @MarieComet and that's not specific to GCF, it's related to the way Gutenberg handles templates. I have a PR in Gutenberg improving this if you want to test it.

https://github.com/WordPress/gutenberg/pull/5162

**Comment by youknowriad** [comment]
I'm closing, thanks @MarieComet let's move the discussion to Gutenberg instead.
