### ISSUE TITLE
Multiple Templates for a given post-type

### ISSUE THREAD

**Issue by Venutius** [youknowriad/gcf#32]
In my current use case I'm using multiple CPT's to create posts of differing fixed content layouts and features. I can see moving to Gutenberg I can create the same effect using templates. However, what would be really nice would be if I could assign multiple templates to a given post type and have the user select the appropriate content structure to be used as differing choices of static layout.

However right now GCF seems to only support one template per post type; you can set up multiple templates ok but there does not seem to be a mechanism for the user to select the template to use. Ideally for example, when they select Add New, I'd like for there to be a sub-menu where they can select the template they want to use. I'd also like to restrict the templates that are available based on the member role.

Is this something that can be done in GCF, am I missing something, or should this be raised with the Gutenberg team direct?

**Comment by youknowriad** [comment]
Hi! Thanks for opening this issue. This is definitely something on the radar but it's more a Gutenberg issue than a GCF one as it's not supported yet in Gutenberg.

I think this is planned for the second iteration of Gutenberg (customization) so we might have to wait a bit to have this feature.

**Comment by Venutius** [comment]
Thanks for the response, I'll be patient!

**Comment by nowrap** [comment]
I tried GCF today with the newest wordpress 5.3 and ran into this issue. I couldn't find an option to switch GCF templates?
