### ISSUE TITLE
Fields are not displaying on the front end

### ISSUE THREAD

**Issue by steveangstrom** [youknowriad/gcf#46]
I create a fieldset, assign it to the post type, I enter data and it all seems fine in Gutenberg. 
When I visit the frontend none of the fields are visible.   All the usual Gutenberg blocks will display as normal on the frontend. I expected the GCF blocks to display the same way.

Gutenberg Version 2.7.0
GCF Version 1.5.1 

user error I'm sure.

![screencapture_03-05-2018-18-gcf-nofrontend](https://user-images.githubusercontent.com/8482649/39595006-25e71b34-4f06-11e8-8673-4ffe5dc52923.gif)

**Comment by youknowriad** [comment]
Yes, this is the correct behavior. See #21 for a detailed explanation. Thanks

**Comment by youknowriad** [comment]
You can also check the docs to see how to render each field on the frontend https://youknowriad.github.io/gcf/#/
