### ISSUE TITLE
planning on making a merge request on trac?

### ISSUE THREAD

**Issue by cfoellmann** [youknowriad/gcf#50]
Do you @youknowriad have plans on making a merge-request for this on the wp core trac?
Any feedback on this already?

**Comment by youknowriad** [comment]
No, this is not going to be merged to WP Core, this has always been plugin territory and will stay that way (meta fields), but templates in general (building a template composed of blocks and not fields) will make its way into Core in Gutenberg V2 phase.

**Comment by cfoellmann** [comment]
thanks.
