### ISSUE TITLE
Ability to lock fields to top and bottom of content, but allow the user to make blocks in-between

### ISSUE THREAD

**Issue by zakaroni** [youknowriad/gcf#57]
This feature would be useful for custom single post templates that have a predefined format for the top and bottom of their blog pages. Here are two possible implementations:

- First, as described in the title:
1.  Select 'split' lock mode.
2.  The GCF template field creation area splits into two areas corresponding to the top and bottom of the Gutenberg editor.

In Gutenberg, users would be able to move the blocks they create in-between, but not move their blocks above or below the header and footer custom fields respectively, so as to preserve their top and bottom position.

![gutenberg1](https://user-images.githubusercontent.com/16501767/43919320-7a2d478c-9c0d-11e8-9dbf-86b41d73f39c.png)

- Second: Creating a new field type that acts like a nested Gutenberg.
![gutenberg2](https://user-images.githubusercontent.com/16501767/43919321-7a542bb8-9c0d-11e8-87db-2071ade70dea.png)

**Comment by youknowriad** [comment]
Actually, what you describe is already possible with GCF:

 - Select "Forbid add/removing blocks" for your template
 - And use a "Free HTML area" field type at the position you want to allow users to create random blocks. The remaining template will be locked but this area will be unlocked.

Let me know if this answers your use-case. Thanks

**Comment by zakaroni** [comment]
You legend, it answers it perfectly. Thank you very much.  👍
