### ISSUE TITLE
Should this plugin work with the Pods Framework?

### ISSUE THREAD

**Issue by mr-king** [youknowriad/gcf#58]
On a fresh install of WP 4.9.8, using the twentyseventeen theme, and using the following plugins:
- gutenberg 3.6.2
- gcf 1.5.5
- pods 2.7.9

I create a new GCF template.  My pods show up as a post type to use it with, but the fields I create in GCF don't show up when adding or editing posts of the types created by Pods.  If I switch to the default Posts or Pages post type, the fields from GCF show up, but when I switch back to my Pods post type, the fields are no longer visible.

Do you know if these fields should be expected to work with post types created by the Pods plugin? Also, to be clear, I'm only concerned with seeing the fields in the administrative backend.

**Comment by youknowriad** [comment]
I'm not familiar with Pods, do these CPTs use the classic editor or Gutenberg? If they open in the classic editor, then GCF won't work there because it's based on Gutenberg.

**Comment by mr-king** [comment]
It looks like it uses the Gutenberg editor.  I just installed the CPT UI plugin, which also can be used to create custom post types and the custom field I created with GCF appears when adding new post types created with CPT UI.

I'm just trying to familiarize myself with Gutenberg, so this isn't urgent at all and you can feel free to close this issue.  Thanks.

**Comment by youknowriad** [comment]
Maybe The Pods Framework is also assigning a Gutenberg Template to the CPT which conflicts with the template assigned by GCF. Since these two plugins have "similar" roles, I think we should probably close this issue, as people will definitely choose a unique Fields Plugin per site.

Thanks
